// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC46lfPFuiZyAZN_xqnIxTEGmCYHlG1hIM',
    appId: '1:748344550395:web:faee4b71890e51ec36615e',
    messagingSenderId: '748344550395',
    projectId: 'flutter-complete-app-d3215',
    authDomain: 'flutter-complete-app-d3215.firebaseapp.com',
    storageBucket: 'flutter-complete-app-d3215.firebasestorage.app',
    measurementId: 'G-JR7FF5PRB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZFLRb5G8TDmNdFGGlELZEzvF_4uJXK84',
    appId: '1:748344550395:android:3233eca75c8dcfdb36615e',
    messagingSenderId: '748344550395',
    projectId: 'flutter-complete-app-d3215',
    storageBucket: 'flutter-complete-app-d3215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuT4vOuDxsp3JKEyYW1Q3zFVo_lMCGyP8',
    appId: '1:748344550395:ios:0da60a5b7ececd0036615e',
    messagingSenderId: '748344550395',
    projectId: 'flutter-complete-app-d3215',
    storageBucket: 'flutter-complete-app-d3215.firebasestorage.app',
    iosBundleId: 'com.example.myHostelApp',
  );
}
